In [2]:
data = 'hello world'
print(data[0])
print(len(data))
print(data)

h
11
hello world


In [3]:
value = 123.1
print(value)
value = 10
print(value)

123.1
10


In [4]:
a = True
b = False
print(a, b)

True False


In [6]:
a, b, c = 1, 2, 3
print(a, b, c)

1 2 3


In [7]:
a = None
print(a)

None


In [9]:
value = 99
if value == 99:
    print('That is fast')
elif value > 200:
    print('That is too fast')
else:
    print('That is safe')

That is fast


In [10]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [11]:
i = 0
while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [12]:
#Tuples
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [15]:
#List
mylist = [1, 2, 3]
print("Zeroth Value: " + str(mylist[0]))

Zeroth Value: 1


In [16]:
mylist.append(4)
print("List Length: " + str(len(mylist)))

List Length: 4


In [17]:
for value in mylist:
    print(value)

1
2
3
4


In [19]:
#Dictionary
mydict = {'a': 1, 'b': 2, 'c': 3}
print("A value: " + str(mydict['a']))

A value: 1


In [22]:
mydict['a'] = 11
print("A value: " + str(mydict['a']))
print(mydict.keys())
print(mydict.values())
for key in mydict.keys():
    print(mydict[key])

A value: 11
dict_keys(['a', 'b', 'c'])
dict_values([11, 2, 3])
11
2
3


In [23]:
def mysum(x, y):
    return(x + y)

result = mysum(1, 3)
print(result)

4


In [25]:
import numpy
mylist = [1, 2, 3]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


In [29]:
import numpy
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)
print("First row: " + str(myarray[0]))

[[1 2 3]
 [3 4 5]]
(2, 3)
First row: [1 2 3]


In [30]:
print("Last row: " + str(myarray[-1]))

Last row: [3 4 5]


In [31]:
print("Specific row and col: " + str(myarray[0, 2]))

Specific row and col: 3


In [32]:
print("Whole col: " + str(myarray[:, 2]))

Whole col: [3 5]


In [33]:
import numpy
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])
print("Addition: " + str(myarray1 + myarray2))
print("Multiplication: " + str(myarray1 * myarray2))

Addition: [5 5 5]
Multiplication: [6 6 6]
